### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by philsturgeon** [gajus/vlad#3]
You suggested people were not so excited about this because it is "unusual" on Reddit, but this is a very common type of package. When people spot "Validation" they will need to be captivated very quickly, or they'll bounce right off the README and not come back.

If you would like some cheap advice it would be: Put a crazy simple piece of example code on the README, then put text and not just code into your actual documentation.

Those docs are hard to look at because of just being code. :)

Also it would be worth outlining what this code does to improve on those other packages, and why. Otherwise its just another validation package on the internet.

**Comment by gajus** [comment]
@philsturgeon To be precise, I said "was/is" unusual. It started with this http://www.reddit.com/r/PHP/comments/1razur/syntactical_php_validation/, then progressed to this https://github.com/gajus/vlad/issues/1 and now it as you see in the units tests. I agree that the current implementation lost character.

Regarding the docs. Are you referring to http://anuary.com/vlad/ or something else (like unit tests)?

> Also it would be worth outlining what this code does to improve on those other packages, and why. Otherwise its just another validation package on the internet.

The main goal was to invent syntax/API/method of rule declaration superior to the existing alternatives. However, I've started thinking that my main goal is 100% DRY. However, it turned out that while rule declaration was much more succinct than the alternatives, it became easier to overlook error. Which is why I've moved to `[[selector collection] => [validator collection], ...]` declaration, where individual selectors cannot reappear in the test script. I am still working on the API and certainly open to suggestions as crazy as they would be.

Second goal is to be able to export validation rules to other interfaces, e.g. frontend javascript validation. This very much remains the goal.

Finally, multilingual support is somewhat lacking in all the alternatives that I've reviewed, including Zend, Laravel and other well established packages. I want to build multilingual support that carries existing dictionary of errors, allows extending errors language level, error level, selector level or selector and error level. I suppose documentation wouldn't hurt to explain these in more detail.

Thank you for your feedback. I will update Vlad with documentation and examples as soon as I settle with the final API.

**Comment by philsturgeon** [comment]
Thanks! I was talking about  http://anuary.com/vlad/ yes, as its just code and that makes it hard to jump in.

Also, since the PHP 4/5/5.2 days (i.e: now that we have PHP 5.3) generally validation systems try to avoid doing all arrays all the time. Arrays are great for allowing flexibility and conventions, but they are also really hard to document, debug and actually use.

Callbacks are commonly used in many of these systems much like blocks in Ruby, to provide documentable objects and methods, instead of HUMUNGOUS multi-dimenstional arrays. That is something you could consider to improve uptake, as people are mostly over huge magic arrays. :)
